/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev */

#ifndef PB_GRIDWARE_PROTOBUF_GRIDWARE_PB_H_INCLUDED
#define PB_GRIDWARE_PROTOBUF_GRIDWARE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _gridware_DeviceResponse {
    bool verified;
} gridware_DeviceResponse;

typedef PB_BYTES_ARRAY_T(2048) gridware_FirmwareImagePage_page_t;
typedef PB_BYTES_ARRAY_T(2) gridware_FirmwareImagePage_crc_t;
typedef struct _gridware_FirmwareImagePage {
    gridware_FirmwareImagePage_page_t page;
    gridware_FirmwareImagePage_crc_t crc;
    bool last;
} gridware_FirmwareImagePage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define gridware_FirmwareImagePage_init_default  {{0, {0}}, {0, {0}}, 0}
#define gridware_DeviceResponse_init_default     {0}
#define gridware_FirmwareImagePage_init_zero     {{0, {0}}, {0, {0}}, 0}
#define gridware_DeviceResponse_init_zero        {0}

/* Field tags (for use in manual encoding/decoding) */
#define gridware_DeviceResponse_verified_tag     1
#define gridware_FirmwareImagePage_page_tag      1
#define gridware_FirmwareImagePage_crc_tag       2
#define gridware_FirmwareImagePage_last_tag      3

/* Struct field encoding specification for nanopb */
#define gridware_FirmwareImagePage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    page,              1) \
X(a, STATIC,   SINGULAR, BYTES,    crc,               2) \
X(a, STATIC,   SINGULAR, BOOL,     last,              3)
#define gridware_FirmwareImagePage_CALLBACK NULL
#define gridware_FirmwareImagePage_DEFAULT NULL

#define gridware_DeviceResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     verified,          1)
#define gridware_DeviceResponse_CALLBACK NULL
#define gridware_DeviceResponse_DEFAULT NULL

extern const pb_msgdesc_t gridware_FirmwareImagePage_msg;
extern const pb_msgdesc_t gridware_DeviceResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gridware_FirmwareImagePage_fields &gridware_FirmwareImagePage_msg
#define gridware_DeviceResponse_fields &gridware_DeviceResponse_msg

/* Maximum encoded size of messages (where known) */
#define gridware_FirmwareImagePage_size          2057
#define gridware_DeviceResponse_size             2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
